modLoader = "javafml" #mandatory
loaderVersion = "${forge_loader_version_range}" #mandatory This is typically bumped every Minecraft version by Forge. See https://files.minecraftforge.net/ for a list of versions.
license = "${license}" # Review your options at https://choosealicense.com/.
issueTrackerURL = "https://github.com/TUsama/Loot-Beams-Refork/issues"
displayURL="https://www.curseforge.com/minecraft/mc-mods/loot-beams-refork"
[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${version}" #mandatory
displayName = "${mod_name}" #mandatory
logoFile = "${mod_id}.png" #optional (needs to be in the root of your mod jar (root of your 'resources' folder))
credits = "Thanks for this example mod goes to Java" #optional
authors = "${mod_author}" #optional
description = '''${description}''' #mandatory (Supports multiline text)
modProperties={fzzy_config="${mod_id}"}
[[dependencies.${mod_id}]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "${forge_version_range}" #mandatory
ordering = "NONE" # The order that this dependency should load in relation to your mod, required to be either 'BEFORE' or 'AFTER' if the dependency is not mandatory
side = "BOTH" # Side this dependency is applied on - 'BOTH', 'CLIENT' or 'SERVER'
[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "fzzy_config"
mandatory = true
versionRange = "[0.5.9,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.${mod_id}]]
modId = "apotheosis"
mandatory = false
versionRange = "[7.2.0,)"
ordering = "AFTER"
side = "CLIENT"
[[dependencies.${mod_id}]]
modId = "mmorpg"
mandatory = false
versionRange = "[5.9.0,)"
ordering = "AFTER"
side = "CLIENT"