modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "${mod_issue_tracker}"
license = "${mod_license}"

[[mods]]
    modId = "${mod_id}"
    version = "${mod_version}"
    displayName = "${mod_name}"
    description = '''${mod_description}'''
    authors = "${mod_author}"

[[dependencies.${mod_id}]]
    modId = "forge"
    mandatory = true
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${mod_id}]]
    modId = "minecraft"
    versionRange = "${target_minecraft}"
    mandatory = true

[[dependencies.${mod_id}]]
    modId = "fzzy_config"
    versionRange = "[${fzzy_config_version},)"
    mandatory = true
[[dependencies.${mod_id}]]
    modId = "commonnetworking"
    mandatory = true